# Generated by Django 5.0.6 on 2024-07-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_age_item_birthday_item_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
