# Generated by Django 5.0.6 on 2024-07-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_age_alter_item_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='mom_first_name',
            new_name='mother_first_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mom_last_name',
            new_name='mother_last_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mom_middle_name',
            new_name='mother_middle_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='mom_occupation',
            new_name='mother_occupation',
        ),
    ]
