# Generated by Django 5.0.6 on 2024-07-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_mom_first_name_item_mother_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='civilstatus',
            new_name='civil_status',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='height',
            new_name='height_CM',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='weight',
            new_name='weight_KG',
        ),
    ]
